### ISSUE TITLE
commads

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [CLADevs/FactionsPE#2]
/f create factionname
/f disband
/f claim
/f unclam
/f kick playername
/f leave
/f tag newfactionname
/f map
/f power
/f top (placed spawners if possible its been done in mcpe)
/f title (for like giving a title to a player like Co-Leader
/f war factionname
/f invite playername
/f accept
/f deny
/f sethome
/f home
/f unsethome
/f setwarp warpname password
/f warp warpname password
/f promote Playername
/f demote Playername
/f who shows faction that you are in
/f who Faction name
/f ally
/f ally accept
/f enemy
/f fclaim factionname
/f funclaim factionname
/f desc (faction desc)
/f over claim (the faction being over claimed must have more claims than power)

**Comment by PotatoeTrainYT** [comment]
whats this issue for?

**Comment by kenygamer** [comment]
@PotatoeTrainYT If you use your brain, you will notice that this is a TODO issue.

**Comment by kenygamer** [comment]
@PotatoeTrainYT He didn't specify, and you can figure out.

**Comment by BurritoMan46** [comment]
He meant you add these that he typed xD
